language: node_js
node_js:
  - "10.0"
  - "9.0"
  - "7.0"
  - "6.0"
  - "5.0"
  - "4.2"
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
services:
  - mongodb
install:
  - npm install mongoose@^4.2.4
  - npm install
